version: '3.3'
services:
  post_db:
    image: mongo:${MONGODVER}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${DOCKHUBUSER}/ui:${APPUIVER}
    ports:
      - ${APPSRCPORT}:${APPDSTPORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${DOCKHUBUSER}/post:${APPPOSTVER}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${DOCKHUBUSER}/comment:${APPCMMNTVER}
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  back_net:
  front_net:
